### ISSUE TITLE
🕷️[BUG/CRASH/GLITCH] ... Startup with Kentie Laucher & DeusExe.u

### ISSUE THREAD

**Issue by MyZones** [onnoj/DeusExEchelonRenderer#29]
When Launching the steam version of DeusEx game of the year edition, I can get the config screen to show, once I select the Echelon Render & launch I get a white screen & the game eventually closes back to desktop
Echelon render version 0.3.9
RTX remix version 0.5.4
Windows 11
Nvidia hardware with driver version 561.09 (installed 12/sept/2024)
NOTE: The other render options do get to the games main menu even if its in windowed mode

Latest Event viewer log shows, this is with a clean "\common\Deus Ex\system" folder
then files validated / downloaded, then Remix extracted, followed by Echelon render

Faulting application name: DeusEx.exe, version: 8.1.0.0, time stamp: 0x56c63d6a
Faulting module name: Core.dll, version: 0.0.0.0, time stamp: 0x3ab15e85
Exception code: 0xc0000005
Fault offset: 0x00045475
Faulting process id: 0x0x2340
Faulting application start time: 0x0x1DB055D3CE35114
Faulting application path: D:\Steam\steamapps\common\Deus Ex\System\DeusEx.exe
Faulting module path: D:\Steam\steamapps\common\Deus Ex\System\Core.dll
Report Id: fdc13800-69b0-41e0-bb11-e41e3f0d5b55
Faulting package full name:
Faulting package-relative application ID:

Faulting application name: DeusEx.exe, version: 8.1.0.0, time stamp: 0x56c63d6a
Faulting module name: MSVCP140.dll, version: 14.36.32532.0, time stamp: 0x691de424
Exception code: 0xc0000005
Fault offset: 0x00015383
Faulting process id: 0x0x2340
Faulting application start time: 0x0x1DB055D3CE35114
Faulting application path: D:\Steam\steamapps\common\Deus Ex\System\DeusEx.exe
Faulting module path: C:\Windows\SYSTEM32\MSVCP140.dll
Report Id: 0fd5cb9c-3144-4afa-a1b9-099fe89f956a
Faulting package full name:
Faulting package-relative application ID: 

Quake 2 RTX launches fine - slow to start but it does start
Portal with RTX (steam) - slow to start but it does start, valve start video lagged

**Comment by onnoj** [comment]
Hi, can you try and attach the log files mentioned here: 
https://github.com/onnoj/DeusExEchelonRenderer/wiki/How-to-collect-debugging-information#collecting-the-log-files

Another thing to try is to set the DPI scaling mode to 'Application', to do this, right click deusex.exe, go to properties, compatibility tab and then click 'change high DPI settings':
![image](https://github.com/user-attachments/assets/ce89d41a-f6c4-43e2-8140-854a2dc7829c)

**Comment by MyZones** [comment]
Log files / memory dump attached
[deusex_d3d9.log](https://github.com/user-attachments/files/16995956/deusex_d3d9.log)
[d3d9.log](https://github.com/user-attachments/files/16995957/d3d9.log)

Managed to get rtx remix to crash when ALT+Tab with white screen - taken as app crashed
Memory Dump at https://filebin.net/hkjzxho3jyv7jy8w
Note this expires in 6 days from 13/09/2024

Alt Location for same file: https://file.io/z5daNVGkIDIN

After multiple launch attempts which still gets a white screen for a while, the game does eventually start - the deusex logo gets a reflection as is circles.
Now Despite the fact I set the resolution via Kentie Launcher to 1280x1024 the in game resolution via settings shows something 
else, cycling the resolutions does not even list this...

DeusEx.ini has 
[WinDrv.WindowsClient]
WindowedViewportX=1280
WindowedViewportY=1000
WindowedColorBits=32
FullscreenViewportX=1280
FullscreenViewportY=1024
FullscreenColorBits=32

Having DPI scaling override on or off makes no difference - currently OFF
Configuration settings in launcher: 
![Kentie Launcher settings](https://github.com/user-attachments/assets/da952e82-4b4d-470c-9ebb-7f6523471a89)

**Comment by onnoj** [comment]
I was able to (partially) reproduce it, but unfortunately it looks like the bug is in Deus Exe, for some reason it tries to span the game across multiple monitors (at least for me).

I've fixed a bug that would prevent that from working, so that should fix the crash at least.
I did notice that I can just move the window where I want to when it does that, either by dragging it or using Windows+ArrowKeys.

You may need to change your window size setting in the Deus Exe options one more time, otherwise it will re-use the invalid setting from previous runs. Alternatively, you could try Borderless Windowed mode one more time.

Download:
https://github.com/onnoj/DeusExEchelonRenderer/releases/tag/v0.3.10

**Comment by MyZones** [comment]
Got v0.3.10 installed overwriting previous version, once launch & set the options I still get a white screen briefly before the game goes to main menu - not crashing back to desktop so I guess that's progress.  

Now event viewer is showing Nvidia remix throwing a wobbler:
Faulting application name: NvRemixBridge.exe, version: 10.0.17763.1, time stamp: 0x66b2ad82
Faulting module name: nvngx_dlssd.dll, version: 3.7.0.0, time stamp: 0x65b301f5
Exception code: 0xc0000409
Fault offset: 0x00000000000b0e99
Faulting process id: 0x0x31EC
Faulting application start time: 0x0x1DB0AADD8FF6A5B
Faulting application path: D:\Steam\steamapps\common\Deus Ex\System\.trex\NvRemixBridge.exe
Faulting module path: D:\Steam\steamapps\common\Deus Ex\System\.trex\nvngx_dlssd.dll
Report Id: 651b547a-3a3c-4c7f-9f0c-15c7f199b5f5
Faulting package full name: 
Faulting package-relative application ID: 

Latest Log files: https://file.io/DzVg2PEMvs2s
There are several entries near bottom of "deusex_d3d9.log" that show "Could not find stage: rtx-remix\mods\DeusExEchelonRenderer"

Q) Where does the in game resolution options get brought in from??, doesn't seem to be from kentie deusex launcher
